// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBti6Wpz-3sKjRYe3J95BCuwpI4PePjBrU',
    appId: '1:924055396949:web:18a66acc8dbf5c9aa92adc',
    messagingSenderId: '924055396949',
    projectId: 'note-taking-app-9fa62',
    authDomain: 'note-taking-app-9fa62.firebaseapp.com',
    storageBucket: 'note-taking-app-9fa62.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsFB2A7h5MrZRzBd95Ny5vKr1nh8Zlfmc',
    appId: '1:924055396949:android:ca9b52135034cd31a92adc',
    messagingSenderId: '924055396949',
    projectId: 'note-taking-app-9fa62',
    storageBucket: 'note-taking-app-9fa62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdRRRjX836DFhB8opdDtasWUPXN17u9Q8',
    appId: '1:924055396949:ios:d23a3f52d1aaec53a92adc',
    messagingSenderId: '924055396949',
    projectId: 'note-taking-app-9fa62',
    storageBucket: 'note-taking-app-9fa62.appspot.com',
    iosClientId: '924055396949-tjiom6bdf016sso07iap5u8ovcd8r5n8.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteTakingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdRRRjX836DFhB8opdDtasWUPXN17u9Q8',
    appId: '1:924055396949:ios:d23a3f52d1aaec53a92adc',
    messagingSenderId: '924055396949',
    projectId: 'note-taking-app-9fa62',
    storageBucket: 'note-taking-app-9fa62.appspot.com',
    iosClientId: '924055396949-tjiom6bdf016sso07iap5u8ovcd8r5n8.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteTakingApp',
  );
}
